### ISSUE TITLE
Multiple databases issue

### ISSUE THREAD

**Issue by pendolf** [doismellburning/django12factor#36]
Django settings get only one db connection url, not three.

Venvs vars:
```
(garage)pendolf at warbook in ~/Projects/garage/garage on master*
$ export | grep URL
declare -x CLIENT_DATABASE_URL="mysql://root@127.0.0.1:3306/apps"
declare -x DATABASE_URL="mysql://root@127.0.0.1:3306/garage"
declare -x BRD_DATABASE_URL="mysql://root@127.0.0.1:3306/brd"
```

Django 1.7.7 settings:
```
import django12factor
d12f = django12factor.factorise()
DEBUG = d12f['DEBUG']
SECRET_KEY = d12f['SECRET_KEY']
DATABASES = d12f['DATABASES']
print DATABASES
```
Output:
```
/Users/pendolf/.virtualenvs/garage/bin/python /Users/pendolf/Projects/garage/garage/manage.py runserver 192.168.8.122:8001
{'default': {'ENGINE': 'django.db.backends.mysql', 'NAME': 'garage', 'HOST': '127.0.0.1', 'USER': 'root', 'PASSWORD': '', 'PORT': 3306}}
```

**Comment by doismellburning** [comment]
Thanks very much for letting me know about this - apologies for the inconvenience!

Can I confirm what version of `django12factor` you're using? Because I have to be honest, I'm overdue on releasing 1.3, which ships with the multiple DB support - can you confirm that you're using an unreleased version please?

I suspect that might be the case, and this is caused by the README on GitHub being slightly misleading - it's the README from the master branch, and not the latest released version.

I'm going to look at rolling a release of 1.3 ASAP as it's long overdue, and moving core documentation out of the README (and probably to readthedocs) - thanks very much for prompting this!

Could you confirm my above suspicions please, or let me know if they're not the case? Thank you, sorry again!

**Comment by pendolf** [comment]
Sorry me, I have not checked version too. I used last version from pypi.
```
$ pip freeze | grep django12factor
django12factor==1.2
```

**Comment by doismellburning** [comment]
No no, not at all - my apologies for lack of release and misleading README! Expect 1.3 very soon :)

**Comment by doismellburning** [comment]
@pendolf Right, 1.3's now out - sorry about that!
